---
title: "Mags combinations"
author: "Farnaz Kamranzad"
date: "2023-02-23"
output: html_document
---


```{r setup, include=FALSE}
start.time <- Sys.time()
knitr::opts_chunk$set(echo = TRUE)
library(ETAS.inlabru)
library(tidyquant)
library(gridExtra)
library(grid)
library(lemon)
library(ggplot2)
library(inlabru)
library(INLA)
library(dplyr)
```


```{r Create synthetic catalogue and plot}
mu <- 0.05
K <- 0.089
alpha <- 2.29
c <- 0.11
p <- 1.08

theta <- list(mu=mu, K=K, alpha=alpha, c=c, p=p)

modelledDuration = 2000

M0 = 2.5

scenario_6_5 <- data.frame(ts=c(500, 1000, 1500), magnitudes=c(6.5, 6.5, 6.5))
scenario_6_0 <- data.frame(ts=c(500, 1000, 1500), magnitudes=c(6.0, 6.0, 6.0))
scenario_5_0 <- data.frame(ts=c(500, 1000, 1500), magnitudes=c(5.0, 5.0, 5.0))
scenario_4_0 <- data.frame(ts=c(500, 1000, 1500), magnitudes=c(4.0, 4.0, 4.0))
scenario_mix <- data.frame(ts=c(500, 1000, 1500), magnitudes=c(6.0, 5.0, 4.0))

samp.scenario_6_5 <- generate.temporal.ETAS.synthetic(theta=theta, beta.p=log(10), M0=M0, T1=0, T2=modelledDuration, Ht=scenario_6_5)
samp.scenario_6_0 <- generate.temporal.ETAS.synthetic(theta=theta, beta.p=log(10), M0=M0, T1=0, T2=modelledDuration, Ht=scenario_6_0)
samp.scenario_5_0 <- generate.temporal.ETAS.synthetic(theta=theta, beta.p=log(10), M0=M0, T1=0, T2=modelledDuration, Ht=scenario_5_0)
samp.scenario_4_0 <- generate.temporal.ETAS.synthetic(theta=theta, beta.p=log(10), M0=M0, T1=0, T2=modelledDuration, Ht=scenario_4_0)
samp.scenario_mix <- generate.temporal.ETAS.synthetic(theta=theta, beta.p=log(10), M0=M0, T1=0, T2=modelledDuration, Ht=scenario_mix)

cat.scenario_6_5 <- bind_rows(samp.scenario_6_5)
cat.scenario_6_0 <- bind_rows(samp.scenario_6_0)
cat.scenario_5_0 <- bind_rows(samp.scenario_5_0)
cat.scenario_4_0 <- bind_rows(samp.scenario_4_0)
cat.scenario_mix <- bind_rows(samp.scenario_mix)
  
cat.scenario_6_5 <- cat.scenario_6_5[order(cat.scenario_6_5$ts),]
cat.scenario_6_0 <- cat.scenario_6_0[order(cat.scenario_6_0$ts),]
cat.scenario_5_0 <- cat.scenario_5_0[order(cat.scenario_5_0$ts),]
cat.scenario_4_0 <- cat.scenario_4_0[order(cat.scenario_4_0$ts),]
cat.scenario_mix <- cat.scenario_mix[order(cat.scenario_mix$ts),]

cat.scenario_6_5$idx <- seq(1,length(cat.scenario_6_5$ts))
cat.scenario_6_0$idx <- seq(1,length(cat.scenario_6_0$ts))
cat.scenario_5_0$idx <- seq(1,length(cat.scenario_5_0$ts))
cat.scenario_4_0$idx <- seq(1,length(cat.scenario_4_0$ts))
cat.scenario_mix$idx <- seq(1,length(cat.scenario_mix$ts))
```


```{r}
M_6_5 <- subset(cat.scenario_6_5, magnitudes>=6.5)
M_6_0 <- subset(cat.scenario_6_0, magnitudes>=6.0)
M_5_0 <- subset(cat.scenario_5_0, magnitudes>=5.0)
M_4_0 <- subset(cat.scenario_4_0, magnitudes>=4.0)
M_mix <- subset(cat.scenario_mix, magnitudes>=4)

ggplot() + 
  geom_point(data = cat.scenario_6_5, aes(x=ts, y=magnitudes), size=0.1, alpha=0.5) +
  geom_point(data=M_6_5, aes(ts, magnitudes), size=3, shape=1, color='red') +
  xlim(0, 2000) + ylim(2,7) +
  ggtitle(paste( "3 × M_6.5 -  nEvents =", length(cat.scenario_6_5$ts) )) +
  geom_vline(xintercept=500, lty=2, color='green') +
  geom_vline(xintercept=1000, lty=2, color='green') +
  geom_vline(xintercept=1500, lty=2, color='green') +
  theme_bw() +
  xlab("Time [days]") +
  ylab("Magnitude")


ggplot() + 
  geom_point(data = cat.scenario_6_0, aes(x=ts, y=magnitudes), size=0.1, alpha=0.5) +
  geom_point(data=M_6_0, aes(ts, magnitudes), size=3, shape=1, color='red') +
  xlim(0, 2000) + ylim(2,7) +
  ggtitle(paste( "3 × M_6.0 -  nEvents =", length(cat.scenario_6_0$ts) )) +
  geom_vline(xintercept=500, lty=2, color='green') +
  geom_vline(xintercept=1000, lty=2, color='green') +
  geom_vline(xintercept=1500, lty=2, color='green') +
  theme_bw() +
  xlab("Time [days]") +
  ylab("Magnitude")


ggplot() + 
  geom_point(data = cat.scenario_5_0, aes(x=ts, y=magnitudes), size=0.1, alpha=0.5) +
  geom_point(data=M_5_0, aes(ts, magnitudes), size=3, shape=1, color='red') +
  xlim(0, 2000) + ylim(2,7) +
  ggtitle(paste( "3 × M_5.0 -  nEvents =", length(cat.scenario_5_0$ts) )) +
  geom_vline(xintercept=500, lty=2, color='green') +
  geom_vline(xintercept=1000, lty=2, color='green') +
  geom_vline(xintercept=1500, lty=2, color='green') +
  theme_bw() +
  xlab("Time [days]") +
  ylab("Magnitude")


ggplot() + 
  geom_point(data = cat.scenario_4_0, aes(x=ts, y=magnitudes), size=0.1, alpha=0.5) +
  geom_point(data=M_4_0, aes(ts, magnitudes), size=3, shape=1, color='red') +
  xlim(0, 2000) + ylim(2,7) +
  ggtitle(paste( "3 × M_4.0 -  nEvents =", length(cat.scenario_4_0$ts) )) +
  geom_vline(xintercept=500, lty=2, color='green') +
  geom_vline(xintercept=1000, lty=2, color='green') +
  geom_vline(xintercept=1500, lty=2, color='green') +
  theme_bw() +
  xlab("Time [days]") +
  ylab("Magnitude")


ggplot() + 
  geom_point(data = cat.scenario_mix, aes(x=ts, y=magnitudes), size=0.1, alpha=0.5) +
  geom_point(data=M_mix, aes(ts, magnitudes), size=3, shape=1, color='red') +
  xlim(0, 2000) + ylim(2,7) +
  ggtitle(paste( "Mix 6, 5, 4 -  nEvents =", length(cat.scenario_mix$ts) )) +
  geom_vline(xintercept=500, lty=2, color='green') +
  geom_vline(xintercept=1000, lty=2, color='green') +
  geom_vline(xintercept=1500, lty=2, color='green') +
  theme_bw() +
  xlab("Time [days]") +
  ylab("Magnitude")

```



# Inversion for scenario M6.5
```{r}
startingValues <- data.frame( mu=c(0.3),
                              K=c(0.1),
                              alpha=c(1.),
                              c=c(0.2),
                              p=c(1.01))

fpath <- system.file("extdata", "user_input_synthetic_noCatalogue.txt", package="ETAS.inlabru")
list.input_6_5 <- create.input.list.temporal.noCatalogue(fpath)

# Tweak the variables laoded from the input file
list.input_6_5$M0 <- M0

i=1
  
list.input_6_5$mu.init <- startingValues$mu[i]
list.input_6_5$alpha.init <- startingValues$alpha[i]
list.input_6_5$K.init <- startingValues$K[i]
list.input_6_5$c.init <- startingValues$c[i]
list.input_6_5$p.init <- startingValues$p[i]

link.f <- list(mu = \(x) gamma.t(x, a_mu, b_mu), 
               K = \(x) loggaus.t(x, a_K, b_K), 
               alpha = \(x) unif.t(x, a_alpha, b_alpha), 
               c_ = \(x) unif.t(x, a_c, b_c), 
               p = \(x) unif.t(x, a_p, b_p))
  
list.input_6_5$th.init <- list(th.mu = inv.gamma.t(list.input_6_5$mu.init, list.input_6_5$a_mu, list.input_6_5$b_mu),
                           th.K = inv.loggaus.t(list.input_6_5$K.init, list.input_6_5$a_K, list.input_6_5$b_K),
                           th.alpha = inv.unif.t(list.input_6_5$alpha.init, list.input_6_5$a_alpha, list.input_6_5$b_alpha),
                           th.c = inv.unif.t(list.input_6_5$c.init, list.input_6_5$a_c, list.input_6_5$b_c),
                           th.p = inv.unif.t(list.input_6_5$p.init, list.input_6_5$a_p, list.input_6_5$b_p) )

startTime <- 0
list.input_6_5$time.int <- c(startTime, modelledDuration)
list.input_6_5$T12 <- c(startTime, modelledDuration)
  

if(is.null(list.input_6_5$max_step)){
  list.input_6_5$bru.opt.list <- list(bru_verbose = 3, # type of visual output 
                                  bru_max_iter = list.input_6_5$max_iter, # maximum number of iterations
                                  num.threads = 5,
                                  #bru_method = list(max_step = 0.5),
                                  inla.mode = 'experimental', # type of inla algorithm
                                  bru_initial = list.input_6_5$th.init) # parameters initial values
  } else {
    list.input_6_5$bru.opt.list <- list(bru_verbose = 3, # type of visual output 
                                    bru_max_iter = list.input_6_5$max_iter, # maximum number of iterations
                                    bru_method = list(max_step = list.input_6_5$max_step),
                                    num.threads = 5,
                                    inla.mode = 'experimental', # type of inla algorithm
                                    bru_initial = list.input_6_5$th.init) # parameters initial values
    }


list.input_6_5$catalog <- cat.scenario_6_5

list.input_6_5$catalog.bru <- data.frame(
  ts = cat.scenario_6_5$ts,
  magnitudes = cat.scenario_6_5$magnitudes,
  idx.p = seq_len(nrow(cat.scenario_6_5))
  )
  
ETAS.model.fit_6_5 <- Temporal.ETAS.fit(list.input_6_5)

i<-1

list.output_6_5 <-list()
list.output_6_5[[i]] <- append(list.input_6_5, list(model.fit=ETAS.model.fit_6_5))
list.output_6_5[[i]]$runtime <- sum(list.input_6_5[[i]]$model.fit$bru_timings$Time)
list.output_6_5[[i]]$nEvents <- length(list.input_6_5[[i]]$catalog[,1])
```


# Inversion for scenario M6.0
```{r}
startingValues <- data.frame( mu=c(0.3),
                              K=c(0.1),
                              alpha=c(1.),
                              c=c(0.2),
                              p=c(1.01))

fpath <- system.file("extdata", "user_input_synthetic_noCatalogue.txt", package="ETAS.inlabru")
list.input_6_0 <- create.input.list.temporal.noCatalogue(fpath)

# Tweak the variables laoded from the input file
list.input_6_0$M0 <- M0

i=1
  
list.input_6_0$mu.init <- startingValues$mu[i]
list.input_6_0$alpha.init <- startingValues$alpha[i]
list.input_6_0$K.init <- startingValues$K[i]
list.input_6_0$c.init <- startingValues$c[i]
list.input_6_0$p.init <- startingValues$p[i]

link.f <- list(mu = \(x) gamma.t(x, a_mu, b_mu), 
               K = \(x) loggaus.t(x, a_K, b_K), 
               alpha = \(x) unif.t(x, a_alpha, b_alpha), 
               c_ = \(x) unif.t(x, a_c, b_c), 
               p = \(x) unif.t(x, a_p, b_p))
  
list.input_6_0$th.init <- list(th.mu = inv.gamma.t(list.input_6_0$mu.init, list.input_6_0$a_mu, list.input_6_0$b_mu),
                           th.K = inv.loggaus.t(list.input_6_0$K.init, list.input_6_0$a_K, list.input_6_0$b_K),
                           th.alpha = inv.unif.t(list.input_6_0$alpha.init, list.input_6_0$a_alpha, list.input_6_0$b_alpha),
                           th.c = inv.unif.t(list.input_6_0$c.init, list.input_6_0$a_c, list.input_6_0$b_c),
                           th.p = inv.unif.t(list.input_6_0$p.init, list.input_6_0$a_p, list.input_6_0$b_p) )

startTime <- 0
list.input_6_0$time.int <- c(startTime, modelledDuration)
list.input_6_0$T12 <- c(startTime, modelledDuration)
  

if(is.null(list.input_6_0$max_step)){
  list.input_6_0$bru.opt.list <- list(bru_verbose = 3, # type of visual output 
                                  bru_max_iter = list.input_6_0$max_iter, # maximum number of iterations
                                  num.threads = 5,
                                  #bru_method = list(max_step = 0.5),
                                  inla.mode = 'experimental', # type of inla algorithm
                                  bru_initial = list.input_6_0$th.init) # parameters initial values
  } else {
    list.input_6_0$bru.opt.list <- list(bru_verbose = 3, # type of visual output 
                                    bru_max_iter = list.input_6_0$max_iter, # maximum number of iterations
                                    bru_method = list(max_step = list.input_6_0$max_step),
                                    num.threads = 5,
                                    inla.mode = 'experimental', # type of inla algorithm
                                    bru_initial = list.input_6_0$th.init) # parameters initial values
    }


list.input_6_0$catalog <- cat.scenario_6_0

list.input_6_0$catalog.bru <- data.frame(
  ts = cat.scenario_6_0$ts,
  magnitudes = cat.scenario_6_0$magnitudes,
  idx.p = seq_len(nrow(cat.scenario_6_0))
  )
  
ETAS.model.fit_6_0 <- Temporal.ETAS.fit(list.input_6_0)

i<-1

list.output_6_0 <-list()
list.output_6_0[[i]] <- append(list.input_6_0, list(model.fit=ETAS.model.fit_6_0))
list.output_6_0[[i]]$runtime <- sum(list.input_6_0[[i]]$model.fit$bru_timings$Time)
list.output_6_0[[i]]$nEvents <- length(list.input_6_0[[i]]$catalog[,1])
```



# Inversion for scenario M5.0
```{r}
startingValues <- data.frame( mu=c(0.3),
                              K=c(0.1),
                              alpha=c(1.),
                              c=c(0.2),
                              p=c(1.01))

fpath <- system.file("extdata", "user_input_synthetic_noCatalogue.txt", package="ETAS.inlabru")
list.input_5_0 <- create.input.list.temporal.noCatalogue(fpath)

# Tweak the variables laoded from the input file
list.input_5_0$M0 <- M0

i=1
  
list.input_5_0$mu.init <- startingValues$mu[i]
list.input_5_0$alpha.init <- startingValues$alpha[i]
list.input_5_0$K.init <- startingValues$K[i]
list.input_5_0$c.init <- startingValues$c[i]
list.input_5_0$p.init <- startingValues$p[i]

link.f <- list(mu = \(x) gamma.t(x, a_mu, b_mu), 
               K = \(x) loggaus.t(x, a_K, b_K), 
               alpha = \(x) unif.t(x, a_alpha, b_alpha), 
               c_ = \(x) unif.t(x, a_c, b_c), 
               p = \(x) unif.t(x, a_p, b_p))
  list.input_5_0
list.input_5_0$th.init <- list(th.mu = inv.gamma.t(list.input_5_0$mu.init, list.input_5_0$a_mu, list.input_5_0$b_mu),
                           th.K = inv.loggaus.t(list.input_5_0$K.init, list.input_5_0$a_K, list.input_5_0$b_K),
                           th.alpha = inv.unif.t(list.input_5_0$alpha.init, list.input_5_0$a_alpha, list.input_5_0$b_alpha),
                           th.c = inv.unif.t(list.input_5_0$c.init, list.input_5_0$a_c, list.input_5_0$b_c),
                           th.p = inv.unif.t(list.input_5_0$p.init, list.input_5_0$a_p, list.input_5_0$b_p) )

startTime <- 0
list.input_5_0$time.int <- c(startTime, modelledDuration)
list.input_5_0$T12 <- c(startTime, modelledDuration)
  

if(is.null(list.input_5_0$max_step)){
  list.input_5_0$bru.opt.list <- list(bru_verbose = 3, # type of visual output 
                                  bru_max_iter = list.input_5_0$max_iter, # maximum number of iterations
                                  num.threads = 5,
                                  #bru_method = list(max_step = 0.5),
                                  inla.mode = 'experimental', # type of inla algorithm
                                  bru_initial = list.input_5_0$th.init) # parameters initial values
  } else {
    list.input_5_0$bru.opt.list <- list(bru_verbose = 3, # type of visual output 
                                    bru_max_iter = list.input_5_0$max_iter, # maximum number of iterations
                                    bru_method = list(max_step = list.input_5_0$max_step),
                                    num.threads = 5,
                                    inla.mode = 'experimental', # type of inla algorithm
                                    bru_initial = list.input_5_0$th.init) # parameters initial values
    }


list.input_5_0$catalog <- cat.scenario_5_0

list.input_5_0$catalog.bru <- data.frame(
  ts = cat.scenario_5_0$ts,
  magnitudes = cat.scenario_5_0$magnitudes,
  idx.p = seq_len(nrow(cat.scenario_5_0))
  )
  
ETAS.model.fit_5_0 <- Temporal.ETAS.fit(list.input_5_0)

i<-1

list.output_5_0 <-list()
list.output_5_0[[i]] <- append(list.input_5_0, list(model.fit=ETAS.model.fit_5_0))
list.output_5_0[[i]]$runtime <- sum(list.input_5_0[[i]]$model.fit$bru_timings$Time)
list.output_5_0[[i]]$nEvents <- length(list.input_5_0[[i]]$catalog[,1])
```




# Inversion for scenario M5.0
```{r}
startingValues <- data.frame( mu=c(0.3),
                              K=c(0.1),
                              alpha=c(1.),
                              c=c(0.2),
                              p=c(1.01))

fpath <- system.file("extdata", "user_input_synthetic_noCatalogue.txt", package="ETAS.inlabru")
list.input_4_0 <- create.input.list.temporal.noCatalogue(fpath)

# Tweak the variables laoded from the input file
list.input_4_0$M0 <- M0

i=1
  
list.input_4_0$mu.init <- startingValues$mu[i]
list.input_4_0$alpha.init <- startingValues$alpha[i]
list.input_4_0$K.init <- startingValues$K[i]
list.input_4_0$c.init <- startingValues$c[i]
list.input_4_0$p.init <- startingValues$p[i]

link.f <- list(mu = \(x) gamma.t(x, a_mu, b_mu), 
               K = \(x) loggaus.t(x, a_K, b_K), 
               alpha = \(x) unif.t(x, a_alpha, b_alpha), 
               c_ = \(x) unif.t(x, a_c, b_c), 
               p = \(x) unif.t(x, a_p, b_p))
  list.input_4_0
list.input_4_0$th.init <- list(th.mu = inv.gamma.t(list.input_4_0$mu.init, list.input_4_0$a_mu, list.input_4_0$b_mu),
                           th.K = inv.loggaus.t(list.input_4_0$K.init, list.input_4_0$a_K, list.input_4_0$b_K),
                           th.alpha = inv.unif.t(list.input_4_0$alpha.init, list.input_4_0$a_alpha, list.input_4_0$b_alpha),
                           th.c = inv.unif.t(list.input_4_0$c.init, list.input_4_0$a_c, list.input_4_0$b_c),
                           th.p = inv.unif.t(list.input_4_0$p.init, list.input_4_0$a_p, list.input_4_0$b_p) )

startTime <- 0
list.input_4_0$time.int <- c(startTime, modelledDuration)
list.input_4_0$T12 <- c(startTime, modelledDuration)
  

if(is.null(list.input_4_0$max_step)){
  list.input_4_0$bru.opt.list <- list(bru_verbose = 3, # type of visual output 
                                  bru_max_iter = list.input_4_0$max_iter, # maximum number of iterations
                                  num.threads = 5,
                                  #bru_method = list(max_step = 0.5),
                                  inla.mode = 'experimental', # type of inla algorithm
                                  bru_initial = list.input_4_0$th.init) # parameters initial values
  } else {
    list.input_4_0$bru.opt.list <- list(bru_verbose = 3, # type of visual output 
                                    bru_max_iter = list.input_4_0$max_iter, # maximum number of iterations
                                    bru_method = list(max_step = list.input_4_0$max_step),
                                    num.threads = 5,
                                    inla.mode = 'experimental', # type of inla algorithm
                                    bru_initial = list.input_4_0$th.init) # parameters initial values
    }


list.input_4_0$catalog <- cat.scenario_4_0

list.input_4_0$catalog.bru <- data.frame(
  ts = cat.scenario_4_0$ts,
  magnitudes = cat.scenario_4_0$magnitudes,
  idx.p = seq_len(nrow(cat.scenario_4_0))
  )
  
ETAS.model.fit_4_0 <- Temporal.ETAS.fit(list.input_4_0)

i<-1

list.output_4_0 <-list()
list.output_4_0[[i]] <- append(list.input_4_0, list(model.fit=ETAS.model.fit_4_0))
list.output_4_0[[i]]$runtime <- sum(list.input_4_0[[i]]$model.fit$bru_timings$Time)
list.output_4_0[[i]]$nEvents <- length(list.input_4_0[[i]]$catalog[,1])
```



# Inversion for scenario M mix
```{r}
startingValues <- data.frame( mu=c(0.3),
                              K=c(0.1),
                              alpha=c(1.),
                              c=c(0.2),
                              p=c(1.01))

fpath <- system.file("extdata", "user_input_synthetic_noCatalogue.txt", package="ETAS.inlabru")
list.input_mix <- create.input.list.temporal.noCatalogue(fpath)

# Tweak the variables laoded from the input file
list.input_mix$M0 <- M0

i=1
  
list.input_mix$mu.init <- startingValues$mu[i]
list.input_mix$alpha.init <- startingValues$alpha[i]
list.input_mix$K.init <- startingValues$K[i]
list.input_mix$c.init <- startingValues$c[i]
list.input_mix$p.init <- startingValues$p[i]

link.f <- list(mu = \(x) gamma.t(x, a_mu, b_mu), 
               K = \(x) loggaus.t(x, a_K, b_K), 
               alpha = \(x) unif.t(x, a_alpha, b_alpha), 
               c_ = \(x) unif.t(x, a_c, b_c), 
               p = \(x) unif.t(x, a_p, b_p))
  list.input_mix
list.input_mix$th.init <- list(th.mu = inv.gamma.t(list.input_mix$mu.init, list.input_mix$a_mu, list.input_mix$b_mu),
                           th.K = inv.loggaus.t(list.input_mix$K.init, list.input_mix$a_K, list.input_mix$b_K),
                           th.alpha = inv.unif.t(list.input_mix$alpha.init, list.input_mix$a_alpha, list.input_mix$b_alpha),
                           th.c = inv.unif.t(list.input_mix$c.init, list.input_mix$a_c, list.input_mix$b_c),
                           th.p = inv.unif.t(list.input_mix$p.init, list.input_mix$a_p, list.input_mix$b_p) )

startTime <- 0
list.input_mix$time.int <- c(startTime, modelledDuration)
list.input_mix$T12 <- c(startTime, modelledDuration)
  

if(is.null(list.input_mix$max_step)){
  list.input_mix$bru.opt.list <- list(bru_verbose = 3, # type of visual output 
                                  bru_max_iter = list.input_mix$max_iter, # maximum number of iterations
                                  num.threads = 5,
                                  #bru_method = list(max_step = 0.5),
                                  inla.mode = 'experimental', # type of inla algorithm
                                  bru_initial = list.input_mix$th.init) # parameters initial values
  } else {
    list.input_mix$bru.opt.list <- list(bru_verbose = 3, # type of visual output 
                                    bru_max_iter = list.input_mix$max_iter, # maximum number of iterations
                                    bru_method = list(max_step = list.input_mix$max_step),
                                    num.threads = 5,
                                    inla.mode = 'experimental', # type of inla algorithm
                                    bru_initial = list.input_mix$th.init) # parameters initial values
    }


list.input_mix$catalog <- cat.scenario_mix

list.input_mix$catalog.bru <- data.frame(
  ts = cat.scenario_mix$ts,
  magnitudes = cat.scenario_mix$magnitudes,
  idx.p = seq_len(nrow(cat.scenario_mix))
  )
  
ETAS.model.fit_mix <- Temporal.ETAS.fit(list.input_mix)

i<-1

list.output_mix <-list()
list.output_mix[[i]] <- append(list.input_mix, list(model.fit=ETAS.model.fit_mix))
list.output_mix[[i]]$runtime <- sum(list.input_mix[[i]]$model.fit$bru_timings$Time)
list.output_mix[[i]]$nEvents <- length(list.input_mix[[i]]$catalog[,1])
```



# Posterior analysis
```{r, fig.height=4, fig.width=15}
plots <- list()

trueParas <- data.frame(value=c(mu, K, alpha,c, p), param=c("mu", "K", "alpha","c", "p"))

post.list_6.5 <- get_posterior_param(input.list= list.output_6_5[[1]])
post.df_6.5 <-  post.list_6.5[[1]]
post.df_6.5$id <- "scenario: 3 x M6.5"

post.list_6.0 <- get_posterior_param(input.list= list.output_6_0[[1]])
post.df_6.0 <-  post.list_6.0[[1]]
post.df_6.0$id <- "scenario: 3 x M6.0"

post.list_5.0 <- get_posterior_param(input.list= list.output_5_0[[1]])
post.df_5.0 <-  post.list_5.0[[1]]
post.df_5.0$id <- "scenario: 3 x M5.0"

post.list_4.0 <- get_posterior_param(input.list= list.output_4_0[[1]])
post.df_4.0 <-  post.list_4.0[[1]]
post.df_4.0$id <- "scenario: 3 x M4.0"

post.list_mix <- get_posterior_param(input.list= list.output_mix[[1]])
post.df_mix <-  post.list_mix[[1]]
post.df_mix$id <- "scenario: 3 x M_mix"

ggplot(NULL, aes(x, y)) + 
  geom_line(data=post.df_6.5, aes(group=id, color='3 × M_6.5'), size=1)+
  geom_line(data=post.df_6.0, aes(group=id, color='3 × M_6.0'), size=1)+
  geom_line(data=post.df_5.0, aes(group=id, color='3 × M_5.0'), size=1)+
  geom_line(data=post.df_4.0, aes(group=id, color='3 × M_4.0'), size=1)+
  geom_line(data=post.df_mix, aes(group=id, color='M_mix (6, 5, 4)'), size=1)+
  facet_wrap(facets = vars(param), scales = 'free', labeller = label_parsed, nrow=1) +
  geom_vline(aes(xintercept = value ), data=trueParas, color='black', linetype=2, label="True value") + 
  labs(color='Catalogue scenario', linetype='Catalogue scenario' ) +
  ggtitle(paste("Comparison of different scenarios" )) +
  xlab("ETAS Posteriors") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust=1))
  #theme(legend.position='hidden')

```



# Computation time
```{r}
end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken
```





