---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ETAS.inlabru

<!-- badges: start -->
<!-- badges: end -->

R package that implements the ETAS Hawkes process for modelling seismicity

The Epidemic Type Aftershock Sequence Model (ETAS) models seismicity as a self exciting sequence where all earthquakes can trigger new events within a brancing sequence. It is widely used in seismology for modelling active earthquake sequences.

One of the challenges with this model is fitting the model parameters. Most methods use Expectation Maximisation to obtain point estimates of the ETAS parameters. Instead, `ETAS.inlabru` is a Bayesian method which returns joint posteriors for the ETAS parameters - this makes it easier to explore how sources of uncertainty introduce systematic bias in parameter estimates. The method is fast, which make a playful exploration of different synthetic scenarios possible. Also, inlabru makes it easy to incorporate a range of spatial and temporal covariates to help condition the ETAS parameters.

The current implementation focuses on the temporal model - but our roadmap is to implement spatial and spatio-temporal models based on recently published work.

Online documentation: https://edinburgh-seismicity-hub.github.io/ETAS.inlabru/

## Authors

- Francesco Serafini
- Dr Mark Naylor, School of GeoSciences, University of Edinburgh
- Prof Finn Lindgren, School of Mathematics, University of Edinburgh
- Dr Kirsty Bayliss, Global Earthquake Model (GEM)

## Installation

For ETAS.inlabru to work, we need to install both R-INLA and inlabru:

For inlabru (see https://inlabru-org.github.io/inlabru/):

* CRAN release,
``` r
install.packages("inlabru")
```
* or development version,
``` r
# install.packages("remotes")
remotes::install_github("inlabru-org/inlabru")
```

For R-INLA (see https://www.r-inla.org/download-install):
``` r
install.packages(
  "INLA",
  repos = c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/testing"),
  dep = TRUE
)
```

You can install the development version of ETAS.inlabru from [GitHub](https://github.com/) with
``` r
# install.packages("remotes")
remotes::install_github("edinburgh-seismicity-hub/ETAS.inlabru")
```

## Terminology and planning suggestions

### File structure in package

- ETAS.triggering.function.R : Contains the ETAS specific model functions
- HawkesProcess.R : Generic Hawkes code that is intended for integration back into inlabru
- generateSyntheticCatalogues.R : Contains the iterative Hawkes functions for generating triggered events but the actual triggering functions reside in the ETAS file above so we could introduce other models here
- temporalBinning.R : Code to generate time bins to make integration scheme efficient
- plottingFunctions.R : lets put all the standard plotting functions into here
- setupInlabruInputs.R : Put the functions for generating input.list in here

## Terminology

- Let's be specific about when we are doing just temporal so we have clear function names for the spatial and spatial-temporal later on
- I changed the theta from `c(mu, K, ...)` to a `df <- data.frame(mu=mu, K=K, alpha=alpha, c=c, p=p)`. This means we should refer to the values as `df$mu` which is unambiguous etc
  - Might this do anything bad?
- Sometimes you used `th` for `theta` and sometimes for historic times...
  - I have tried to modify to just `theta`

# What has been done

## Implemented

- Generation of synthetic ETAS catalogues by `ETAS.inlabru` with a demonstration in the notebook

## In development

- Add inversion modelling based on original code
- Modify the implementation so that the generic Hawkes code can go into inlabru and the ETAS triggering function code stay in this package
- Develop and implement temporal incompleteness censoring model (Kanranzad)
- Add article on exploratory data analysis of earthquake catalogues (Naylor)
- Add article on preconditioning the model domain on historic earthquakes (Naylor)

## Roadmap

- Anisotropic spatial kernels
- Implementation of spatial model in `ETAS.inlabru` based on work of Bayliss
- Implementation of spatio-temporal model in `ETAS.inlabru` based on work of Serafini
