---
title: "Priors"
author: "Naylor"
date: "2022-12-12"
output: html_document
---
# Plot the priors and samples from the triggering functions

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ETAS.inlabru)

library(tidyquant)
library(gridExtra)
library(grid)
library(lemon)
library(ggplot2)
library(tidyquant)
library(ggpubr)

library(inlabru)
library(INLA)

library(dplyr)


```


## Define the parameters for the syntheirc catalogues and starting values for inversion

```{r Create synthetic catalogue and plot}

# Parameters we use to generate synthetics, which we will refer to as the 'true' parameters
mu <- 0.1
K <- 0.089
alpha <- 2.29
c <- 0.11
p <- 1.08

# Format the true ETAS parameters for code to generate the synthetics
theta_etas <- data.frame(mu=mu, K=K, alpha=alpha, c=c, p=p)

# A dataframe containing different starting values for the algorithm
startingValues <- data.frame( mu=c( 0.3),
                              K=c( 0.1),
                              alpha=c( 1.),
                              c=c( 0.2),
                              p=c(1.01))
nRealisations <- length(startingValues$mu)


# Temporal duration of the synthetic catalogue in days
modelledDuration = 1000  # [days]

# The minimum magnitude that will be modelled
M0 = 2.5

```

# Plot the priors

```{r Plot the priors with true values}

  # Load a set of parameters that we will need to tweak for this application
fpath <- system.file("extdata", "user_input_synthetic_noCatalogue.txt", package="ETAS.inlabru")
list.input <- create.input.list.temporal.noCatalogue(fpath)
list.input$M0 <-M0

mu_priorPlot <- ggplot() +
geom_density(aes(x = list.input$link.functions$mu(rnorm(100000))) ) +
geom_vline(aes(xintercept = mu, color='True value')) +
geom_vline(aes(xintercept = list.input$mu.init, color='Initial value')) +
xlab("mu") +
ggtitle("A.  mu prior")+
    theme_bw() + 
  theme(plot.title = element_text(size = 9))+
       theme(legend.position = c(.7, .7))

K_priorPlot <- ggplot() +
geom_density(aes(x = list.input$link.functions$K(rnorm(100000))) , show.legend = FALSE) +
geom_vline(aes(xintercept = K, color='True value'), show.legend = FALSE) +
geom_vline(aes(xintercept = list.input$K.init, color='Initial value'), show.legend = FALSE) +
xlab("K") +
    theme_bw() + 
  theme(plot.title = element_text(size = 9))+
ggtitle("B.  K prior")  

alpha_priorPlot <- ggplot() +
geom_density(aes(x = list.input$link.functions$alpha(rnorm(100000))) ) +
geom_vline(aes(xintercept = alpha, color='True value'), show.legend = FALSE) +
geom_vline(aes(xintercept = list.input$alpha.init, color='Initial value'), show.legend = FALSE) + 
  xlab("alpha") +
    theme_bw() + 
  theme(plot.title = element_text(size = 9))+
ggtitle("C.  alpha prior")

c_priorPlot <- ggplot() +
geom_density(aes(x = list.input$link.functions$c(rnorm(100000))) ) +
geom_vline(aes(xintercept = c, color='True value'), show.legend = FALSE) +
geom_vline(aes(xintercept = list.input$c.init, color='Initial value'), show.legend = FALSE) +
  xlab("c") +
    theme_bw() + 
  theme(plot.title = element_text(size = 9))+
  ggtitle("D.  c prior")

p_priorPlot <- ggplot() +
geom_density(aes(x = list.input$link.functions$p(rnorm(100000))) ) +
geom_vline(aes(xintercept = p, color='True value'), show.legend = FALSE) +
geom_vline(aes(xintercept = list.input$p.init, color='Initial value'), show.legend = FALSE) +
  xlab("p") +
  theme_bw() + 
  theme(plot.title = element_text(size = 9))+
ggtitle("E.  p prior")

plt <- grid_arrange_shared_legend(mu_priorPlot, K_priorPlot,alpha_priorPlot,c_priorPlot,p_priorPlot, ncol=3, nrow=2, position='bottom', top="Samples from the priors")
ggsave("priors.png", plt)
ggsave("priors.pdf", plt)

```

## Explore ETAS triggering function using samples from the prior

```{r}
n.samp <- 1000
prior.samp <- cbind( list.input$link.functions$mu(rnorm(n.samp)),
list.input$link.functions$K(rnorm(n.samp)),
list.input$link.functions$alpha(rnorm(n.samp)),
list.input$link.functions$c(rnorm(n.samp)),
list.input$link.functions$p(rnorm(n.samp)))

head(prior.samp)
```


```{r}
plot_triggering <- list()
plot_triggering[[1]] <- triggering_fun_plot_priors(list.input, magnitude = 4, n.samp = 1000) +
  ggtitle("G. M4 trig. func.") +    
  xlab("Time [days]")+
  theme_bw()  + 
  theme(plot.title = element_text(size = 9))

plot_triggering[[3]] <- triggering_fun_plot_priors(list.input, magnitude = 6.7, n.samp = 1000) +
  ggtitle("H. M6.7 trig. func.") +     
  xlab("Time [days]")+
  theme_bw() + 
  theme(plot.title = element_text(size = 9))


plt <- grid.arrange(plot_triggering[[1]], plot_triggering[[3]], ncol=2, nrow=1, top="Triggering function variability") + 
  theme(plot.title = element_text(size = 9))

#ggsave("trig_priorSamples.png", plt)
#ggsave("trig_priorSamples.pdf", plt)
```

```{r}
plot_omori <- list()
plot_omori[[1]] <- omori_plot(list.input, n.samp = 1000) +
  ggtitle("F. Omori decay") +     
  theme_bw()  + 
  xlab("Time [days]") +
  ylim(0,1) + 
  theme(plot.title = element_text(size = 9))


```

```{r}

plt <- grid.arrange(plot_omori[[1]], plot_triggering[[1]], plot_triggering[[3]], ncol=3, top="Samples of the triggering function from the ETAS priors") 

ggsave("trigFuncVariability_priors.png", plt)
ggsave("trigFuncVariability_priors.pdf", plt)
```

```{r}

plt <- grid_arrange_shared_legend(mu_priorPlot, K_priorPlot,alpha_priorPlot,c_priorPlot,p_priorPlot, plot_omori[[1]], plot_triggering[[1]], plot_triggering[[3]], ncol=4, nrow=2, position='top')
ggsave("priors_comb.png", plt)
ggsave("priors_comb.pdf", plt)
```

